### ISSUE TITLE
Sai2 support?

### ISSUE THREAD

**Issue by nikitalita** [Wunkolo/libsai#14]
Have you taken a look at reverse engineering Sai 2 files? It seems to be a different format; the header is unencrypted, has the identifier `SAI-CANVAS-TYPE0`, and has a bunch of readable file information, like history, thumbnails, layers, etc. I was just wondering how different it actually is compared to Sai 1 files besides the header and how comparatively difficult it would be to make this work with them.

**Comment by Wunkolo** [comment]
Sai2 certainly looks a lot more trivial than Sai1 files, I've peeked at it and reverse engineered some of the beta releases of Sai2. Lots of people on the [itch.io page](https://wunkolo.itch.io/saithumbs) are also asking for Sai2. Though the issue is really just that there isn't much incentive for me to focus and dedicate on it. Many people I had known that would have benefited from it are either sticking with Sai1 or moved onto Clip Studio or something. There is also a [long-standing bug](https://github.com/Wunkolo/libsai/issues/6) with `libsai` that holds me back from moving onto making `libsai2` knowing the Sai1 library is not exactly in a state for me to fully shelf it.
Totally willing to aid others on their journey though, but I can't faithfully sustain a project like that on my own at the moment.

**Comment by nikitalita** [comment]
understood; there's not a lot of incentive to do so when both versions support exporting to Photoshop. I just wanted it so I could convert Sai2 files without having to pay for a full version, though I might just do so out of spite so I can take a crack at this myself. 

What sort of techniques did you use to reverse engineer the file format? Also, how obfuscated is Painttool Sai itself? I imagine it's using some form of obfuscation, as a lot of old-timey proprietary Japanese hobbyist software does.

**Comment by Wunkolo** [comment]
> What sort of techniques did you use to reverse engineer the file format?

Typical IDA Pro reverse engineering pipeline. I looked for imported WinAPI functions like [ReadFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile) and went up the callstacks from there and started reverse engineering its architecture around reading/writing files in general, and then reading/writing .sai files in particular and what data-structures/arithmetic it used. Lots of runtime debugging with simple sample files. Stepping through it reading encrypted data and decrypting it and mimicking it in my own code. It's a forensic skill that touches a lot of what you may know about both low-level and high-level concepts of computer 

> Also, how obfuscated is Painttool Sai itself? I imagine it's using some form of obfuscation, as a lot of old-timey proprietary Japanese hobbyist software does.

It actually doesn't seem protected or packed or anything at all. Just plain release-mode output from MSVC from what I've seen.

**Comment by photopea** [comment]
@Wunkolo I made a SAI parser and a decoder, which is a part of my web-based tool www.photopea.com (just drag-and-drop a SAI file into it).

I am making a SAI2 parser, and I can decode the basic structure of a file. There is a "lpix" section for each layer, which is supposed to contain pixel data for each layer. However, I am not able to decode it.

@Wunkolo could you maybe take a look at this compression? It is probably not RLE. When I make a pixel of a specific color, e.g. RGB 200,201,202, none of the values (200, 201 or 202) occurs in the byte stream (it must occur in PackBits RLE).

When I made two single-layer SAI2 files, 256x256 pixel. One contains a "checkerboard" of white/black pixels. Another contains "black / white vertical stripes", that are 1 pixel wide.

The "lpix" section of a checkerboard uses 9 Bytes per pixel, while for the stripes, it uses 0.34 Bytes per pixel. So I think there could be a Wavelet decomposition involved at some point. Or some "predictor filter" that can copy the pixels "from above".

This compression should not be that complicated, because even DEFLATE can shrink these files a lot (see the ZIP archive below).

[sai2.zip](https://github.com/user-attachments/files/18814856/sai2.zip)

**Comment by Wunkolo** [comment]
Hey! I've been slowly chipping away at Sai2 over the course of quite some time. It's a huge effort so I've only been able to chip away at it at a partial capacity besides other full-time obligations but what I've found so far is that Sai2 technically as a few formats where it stores its raster data. One is `jssf`(seems to not be used much), `raw`(which is just an already-decompressed `dpcm`), and the primary one you'll see most-often is `dpcm` which is used practically everywhere as `mpix`(mask data), `lpix`(the actual layer data), `fpix`(not exactly sure, but each layer can have an this data in addition to the mask data). 

It looks like tiles are 256x256 and the `dpcm` stream is first composed of a bunch of 32-bit integers of run-time data that is likely the bit-map for active tiles like in the original sai(the exact number and format of this chunk of data seems to be calculated from the actual `layr` data and some runtime factors that I am still figuring out) and then it is immediately followed by the **compressed** raster data that is compressed per-channel just like the original SAI. You're right that it is not using the same Sai1 routine or a typical form of RLE.

The channel data itself are 16-bit values and seems to use a modified RLE of sorts that only actually has two cases of opcodes. The only "runs" it seems to support are runs of `0`-values, and tightly packed bit-data where the "opcode" itself also encodes some data. It's a bit difficult to explain and I'm still mapping out the format itself.

Here's what I deciphered so far from the assembly:

```cpp
__int64 __fastcall UnpackRasterData(
        unsigned int *Data,
        __int16 *PixelData,
        unsigned int PixelWriteCount,
        unsigned int OutputChannels,
        unsigned int InputChannels)
{
  __int64 OutputChannels_1; // rbp
  __int64 PixelWriteCount_1; // r12
  unsigned int *CurDataWord; // rsi
  unsigned __int64 CurControlMask64; // r10
  unsigned int RemainingBits; // ebx
  unsigned int CurrentChannel; // r13d
  int v12; // r8d
  unsigned int PixelCount; // edi
  __int16 *DstData; // r9
  char ShiftAmount; // cl
  __int64 FirstSetBitIdx; // rdx
  unsigned __int64 FirstSetBit; // r10
  char FirstSetBit_1; // r11
  unsigned int CurOpCode; // r11d
  int BitActiveMask; // ecx
  __int16 ChannelValue; // r8
  char ControlMask_1; // al
  __int64 ZeroFillCount; // rax
  __int16 *CurPixel; // rcx
  __int64 CurPixel_1; // rax
  int v28; // [rsp+30h] [rbp+8h]

  v28 = (int)Data;
  OutputChannels_1 = OutputChannels;
  PixelWriteCount_1 = PixelWriteCount;
  CurDataWord = Data;
  CurControlMask64 = 0i64;
  RemainingBits = 0;
  CurrentChannel = 0;
  v12 = (int)Data;
  if ( InputChannels )
  {
    do
    {
      PixelCount = 0;
      DstData = &PixelData[CurrentChannel];
      if ( (_DWORD)PixelWriteCount_1 )
      {
        while ( 1 )
        {
          if ( RemainingBits < 32 )
          {
            ShiftAmount = RemainingBits;
            RemainingBits += 32;
            CurControlMask64 |= (unsigned __int64)*CurDataWord++ << ShiftAmount;// Consume another 32-bit integer and append it to the 64-bit control mask
          }
          if ( !_BitScanForward64((unsigned __int64 *)&FirstSetBitIdx, CurControlMask64) )
            return 0i64;
          FirstSetBit = CurControlMask64 >> ((unsigned __int8)FirstSetBitIdx + 1);
          FirstSetBit_1 = FirstSetBit;
          CurControlMask64 = FirstSetBit >> 1;
          CurOpCode = (2 * FirstSetBitIdx) | FirstSetBit_1 & 1;
          RemainingBits += -2 - FirstSetBitIdx;
          if ( !CurOpCode )                     // `0x0` ends the current channel
            break;
          if ( CurOpCode <= 0xE )               // `0x1`-`0xE` involves some actual data
          {
            BitActiveMask = -(((unsigned int)CurControlMask64 & (1 << CurOpCode)) != 0i64);// 111... or 000... depending on if the opcode bit index is set or not?
            ++PixelCount;
            RemainingBits += -1 - CurOpCode;    // The opcode index itself is the number of bits to consume
            ChannelValue = (BitActiveMask & 1)  // Generate the actual channel value based
                         + (BitActiveMask ^ (((1 << CurOpCode) | CurControlMask64 & ((1 << CurOpCode) - 1)) - 1));
            CurControlMask64 >>= (unsigned __int8)CurOpCode + 1;
            *DstData = ChannelValue;            // The actual 16bpc data is written here
NextPixel:
            DstData += OutputChannels_1;        // Move to next pixel
            goto PixelLoopEnd;
          }
          if ( CurOpCode != 0xF )               // `0xF` fills with `0`-values
            return 0i64;
          ControlMask_1 = CurControlMask64;     // Consume the next 7 bits of the control mask
          RemainingBits -= 7;
          CurControlMask64 >>= 7;
          ZeroFillCount = (ControlMask_1 & 0x7Fu) + 8;// These 7 bits are the number of pixel-channel-values to fill
          if ( (_DWORD)ZeroFillCount )
          {
            PixelCount += ZeroFillCount;
            do                                  // Write the `0` values
            {
              *DstData = 0;
              DstData += OutputChannels_1;
              --ZeroFillCount;
            }
            while ( ZeroFillCount );
          }
PixelLoopEnd:
          if ( PixelCount >= (unsigned int)PixelWriteCount_1 )
            goto ChannelLoopEnd;
        }
        *DstData = 0;
        ++PixelCount;
        goto NextPixel;
      }
ChannelLoopEnd:
      ++CurrentChannel;
    }
    while ( CurrentChannel < InputChannels );
    v12 = v28;
  }
  if ( InputChannels < (unsigned int)OutputChannels_1 )// Pad unused channels with 0
  {
    CurPixel = &PixelData[CurrentChannel];
    if ( (_DWORD)PixelWriteCount_1 )
    {
      CurPixel_1 = PixelWriteCount_1;
      do
      {
        *CurPixel = 0;
        CurPixel += OutputChannels_1;
        --CurPixel_1;
      }
      while ( CurPixel_1 );
    }
  }
  if ( RemainingBits >= 8 )
    CurDataWord = (unsigned int *)((char *)CurDataWord - ((unsigned __int64)RemainingBits >> 3));
  return (unsigned int)((_DWORD)CurDataWord - v12);
}
```

**Comment by photopea** [comment]
The "layr" chunk contains "N" - a number of 256x256 pixel tiles inside the "lpix" chunk of that layer.

*** The "intg" has the same format as the "lpix" chunk, but the number "N" of 256x256 tiles in it is ceil(width / 256) x ceil(height / 256)  - I am talking abot the image width and the height.

The "lpix" chunk starts with a string "dpcm", followed by N four-byte integers: the lengths of the compressed content of each 256x256 tile (so the sum of these N integers is the length of the rest of the "lpix" chunk). Then, I think you should look at these N chunks of bytes and decompress each of them into a 256x256 pixel image independently.

Did you do any tests with your code? Are you getting a correct output?

**Comment by Wunkolo** [comment]
This code I shared is decompiled/reverse-engineered output from the sai2.exe executable that describes how this custom RLE stream is read by the application, not from any extraction-code I have made. I am still reverse engineering the file format and have not written any extraction code just yet.

**Comment by photopea** [comment]
Did you make any progress?

**Comment by Wunkolo** [comment]
Yes, I have some local experimental code where I am testing tile extraction still. I'll add it to the repo once it is in a more stable state under MIT license.

**Comment by photopea** [comment]
Thanks a lot! :) Your work is truly valuable!

**Comment by Wunkolo** [comment]
Just an update, I have tile-extraction working over here now. It can successfully extract just a singular tile of what appears to be thumbnail data from a .sai2 canvas, not full canvases just yet but the format of extracting a tile is fully implemented(seems to be a mix of delta-compression between pixels within a row and entire rows of a tile).

https://github.com/Wunkolo/libsai/blob/1f3960e9ba1e8a2968595be6036b2beecb434c10/samples/Thumbnail-Sai2.cpp

I am able to extract the thumbnails out of small `.sai2` file with this now, including your sample-files.

![Image](https://github.com/user-attachments/assets/9539382a-29a7-4177-ab97-e16a4e681569)

![Image](https://github.com/user-attachments/assets/e0d55ce7-cc36-410f-9bca-1338a7c53c91) 

Though any canvas larger than 256x256 will fail to extract since I am still working on tile iteration(there is some kinda complex checksums and arithmetic going on here).

I'll post further updates in the PR from now on!

**Comment by Wunkolo** [comment]
I do intend to make a write-up at some point when I can at least generally extract thumbnails, and then layers, similar to Sai 1.0. Though until then, I'm here to primarily maintain libsai. Until I make this write-up, most of that information will exist in the C++ code and comments that I will be writing for libsai first. There is not much use in making extra work for myself by making a write-up now for others to implement while I am still figuring things out for myself. Sorry!

Until then, I'd follow along with the pull-request(https://github.com/Wunkolo/libsai/pull/20).
